// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// drop_zero_cols_cpp
IntegerMatrix drop_zero_cols_cpp(const IntegerMatrix& mat);
RcppExport SEXP _FAMEFMR_drop_zero_cols_cpp(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(drop_zero_cols_cpp(mat));
    return rcpp_result_gen;
END_RCPP
}
// shift_zero_in_place_cpp
void shift_zero_in_place_cpp(IntegerMatrix x);
RcppExport SEXP _FAMEFMR_shift_zero_in_place_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type x(xSEXP);
    shift_zero_in_place_cpp(x);
    return R_NilValue;
END_RCPP
}
// shift_zero_cpp
IntegerMatrix shift_zero_cpp(IntegerMatrix x);
RcppExport SEXP _FAMEFMR_shift_zero_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(shift_zero_cpp(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FAMEFMR_drop_zero_cols_cpp", (DL_FUNC) &_FAMEFMR_drop_zero_cols_cpp, 1},
    {"_FAMEFMR_shift_zero_in_place_cpp", (DL_FUNC) &_FAMEFMR_shift_zero_in_place_cpp, 1},
    {"_FAMEFMR_shift_zero_cpp", (DL_FUNC) &_FAMEFMR_shift_zero_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_FAMEFMR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
