// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// extract_season_firetypes
List extract_season_firetypes(NumericMatrix v, CharacterVector colnames);
RcppExport SEXP _FAMEFMR_extract_season_firetypes(SEXP vSEXP, SEXP colnamesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type v(vSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type colnames(colnamesSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_season_firetypes(v, colnames));
    return rcpp_result_gen;
END_RCPP
}
// extract_season_firetypes_with_group_id
List extract_season_firetypes_with_group_id(NumericMatrix v, CharacterVector colnames);
RcppExport SEXP _FAMEFMR_extract_season_firetypes_with_group_id(SEXP vSEXP, SEXP colnamesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type v(vSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type colnames(colnamesSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_season_firetypes_with_group_id(v, colnames));
    return rcpp_result_gen;
END_RCPP
}
// leftPackMissingOMP_trim
NumericMatrix leftPackMissingOMP_trim(NumericMatrix mat);
RcppExport SEXP _FAMEFMR_leftPackMissingOMP_trim(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(leftPackMissingOMP_trim(mat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FAMEFMR_extract_season_firetypes", (DL_FUNC) &_FAMEFMR_extract_season_firetypes, 2},
    {"_FAMEFMR_extract_season_firetypes_with_group_id", (DL_FUNC) &_FAMEFMR_extract_season_firetypes_with_group_id, 2},
    {"_FAMEFMR_leftPackMissingOMP_trim", (DL_FUNC) &_FAMEFMR_leftPackMissingOMP_trim, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_FAMEFMR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
