# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

drop_zero_cols_cpp <- function(mat) {
    .Call(`_FAMEFMR_drop_zero_cols_cpp`, mat)
}

shift_zero_in_place_cpp <- function(x) {
    invisible(.Call(`_FAMEFMR_shift_zero_in_place_cpp`, x))
}

shift_zero_cpp <- function(x) {
    .Call(`_FAMEFMR_shift_zero_cpp`, x)
}

