# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

extract_season_firetypes <- function(v, colnames) {
    .Call('_FAMEFMR_extract_season_firetypes', PACKAGE = 'FAMEFMR', v, colnames)
}

extract_combined_season_firetype_with_group_id <- function(v, colnames) {
    .Call('_FAMEFMR_extract_combined_season_firetype_with_group_id', PACKAGE = 'FAMEFMR', v, colnames)
}

leftPackMissingOMP_trim <- function(mat) {
    .Call('_FAMEFMR_leftPackMissingOMP_trim', PACKAGE = 'FAMEFMR', mat)
}

